# Generated by Django 5.2.1 on 2025-08-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='역할 이름')),
            ],
            options={
                'verbose_name': '역할',
                'verbose_name_plural': '역할',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammember', verbose_name='팀원')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role_distribution.role', verbose_name='할당 역할')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='팀')),
            ],
            options={
                'verbose_name': '역할 할당',
                'verbose_name_plural': '역할 할당',
                'unique_together': {('member', 'role')},
            },
        ),
    ]
