# Generated by Django 5.2.1 on 2025-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('favicon_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
