# Generated by Django 5.2.4 on 2025-07-24 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_period_start', models.DateField(blank=True, null=True)),
                ('team_period_end', models.DateField(blank=True, null=True)),
                ('unique_url_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team',
                'ordering': ['-created_at'],
            },
        ),
    ]
