# Generated by Django 5.2.1 on 2025-08-09 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_period_end',
            new_name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_period_start',
        ),
        migrations.RemoveField(
            model_name='team',
            name='unique_url_token',
        ),
        migrations.AddField(
            model_name='team',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='team',
            table=None,
        ),
    ]
