# Generated by Django 5.2.1 on 2025-08-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('assignee', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='team.team')),
            ],
        ),
    ]
